# Tensor Operand
张量是将向量向高维度推广的产品. <br/>
矩阵是一张表，推广后得到的三阶张量是一个魔方，三阶以上是不能直接想象到的. <br/>
建立在张量上的基本运算包括：卷积、膨胀卷积、反卷积、矩阵乘法、哈达玛积等. <br/>
张量运算一个繁琐的细节在于匹配维度. <br/>

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Layer, Dense
import numpy as np
import matplotlib as plt

转置<br/>
转置(Transpose)本质上是将张量内元素的索引(Index)调换顺序(Permutation)

In [3]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
tf.transpose(x, perm=[0, 2, 1]) # By default, perm=[2, 1, 0].

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])>

线性空间<br/>
张量可以映射到相应维度的坐标系中，Axis 就是坐标轴的编号<br/>
在笛卡尔坐标中 x/y/z 分别对映 Axis 0/1/2<br/>
-1表示从后向前数第一个，-2表示从后向前数第二个，依次类推

In [10]:
tf.linspace([0., 5.], [10., 40.], 5, axis=-2)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.  ,  5.  ],
       [ 2.5 , 13.75],
       [ 5.  , 22.5 ],
       [ 7.5 , 31.25],
       [10.  , 40.  ]], dtype=float32)>

堆叠<br/>
堆叠(Stack)是张量独有的运算<br/>
N阶张量与N-1阶张量的关系，类似于数组与元素的关系<br/>
这里的Axis指的是选择哪一维坐标作为"数组"的索引

In [11]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
tf.stack([x, y, z], axis=1) # By default, axis=0.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

仿射<br/>
仿射变换(Reshape)是张量独有的运算<br/>
从一个张量空间映射到另一个张量空间

In [12]:
t1 = [[1, 2, 3],
      [4, 5, 6]]
tf.reshape(t1, [-1]) # 将矩阵（二阶张量）展开成向量（一阶张量）

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

收缩<br/>
收缩(Contraction)是张量独有的运算<br/>
收缩推广了矩阵乘法，而矩阵乘法推广了向量内积<br/>
可以写成爱因斯坦求和记号

In [35]:
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[1, 2], [3, 4]])
tf.tensordot(x, y, axes=[[1], [0]])

<tf.Tensor: shape=(), dtype=int32, numpy=30>

折叠<br/>
折叠（Squeeze）是张量独有的运算<br/>
将投影为单个点的维度折叠

In [13]:
plump = [[1], [2], [3]]
tf.squeeze(plump)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>